#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
    python excel_to_data.py fixed_Kvalues.xlsx ./data.js
"""

import sys
import json
from openpyxl import load_workbook

def xlsx_to_datajs(xlsx_path = "./fixed_kvalues.xlsx", output_path = "./data.js"):
    wb = load_workbook(xlsx_path, read_only=True)
    
    palette = [
        "#D9A227","#8C8C8C","#B5651D","#5A6B6B","#C9922E","#7A7A7A",
        "#A67C3D","#6E7B6E","#D4AF37","#4F5B62","#C84C1A","#6B8E7F",
        "#E8A13D","#5C6B75","#B8860B","#6C7B8C","#D2B48C","#556B2F",
        "#8B4513","#4682B4","#CD853F","#696969","#2F4F4F","#A0522D"
    ]
    
    skip_sheets = {"Sheet1", ""}
    categories = []
    
    for i, sheet_name in enumerate(wb.sheetnames):
        if sheet_name in skip_sheets:
            continue
        
        ws = wb[sheet_name]
        items = []
        
        for row in ws.iter_rows(min_row=2, values_only=True):
            if not row or len(row) < 7:
                continue
            
            total, unit_cost, cost, curr_bal, prev_bal, item_name, code = row[:7]
            if not item_name:
                continue
            
            try:
                price = round(float(unit_cost)) if unit_cost is not None else 0
                stock = round(float(curr_bal)) if curr_bal is not None else 0
            except (ValueError, TypeError):
                price = 0
                stock = 0
            
            code_str = str(code).strip() if code is not None else ""
            
            items.append({
                "name": str(item_name).strip(),
                "price": f"{price} ج",
                "stock": stock,
                "image": f"images/{code_str}.jpg"
            })
        
        if items:
            categories.append({
                "id": f"cat{i}",
                "name": sheet_name.strip(),
                "color": palette[i % len(palette)],
                "description": "",
                "items": items
            })
    
    # كتابة ملف data.js
    header = """/* ============================================================
   بيانات المحل — تم الاستيراد تلقائي من ملف المخزون
   generated by excel_to_data.py
   ============================================================ */

const STORE = {
  name: "مان",
  tagline: "كل حاجة لمشروعك... حديد، عدد، أدوات، دهانات ومستلزمات بناء",
  facebookUrl: "https://www.facebook.com/share/1DC2NMfTsg/?mibextid=wwXIfr",
  locationUrl: "https://maps.app.goo.gl/Qc7UVDHUDSPv13rm6",
  phone: "01111911645",
  address: "مدينة طيبة خلف الجهاز"
};

const categories = """
    
    js_data = json.dumps(categories, ensure_ascii=False, indent=2)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(header + js_data + ";\n")
    
    total_items = sum(len(c["items"]) for c in categories)
    print(f"✓ تم إنشاء {output_path}")
    print(f"  {len(categories)} تصنيف")
    print(f"  {total_items} منتج")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("الاستخدام:")
        print("  python3 excel_to_data.py inventory.xlsx data.js")
        print("\nمثال:")
        print("  python3 excel_to_data.py 1785753638347_fixed_kvalues.xlsx store-site/data.js")
        sys.exit(1)
    
    xlsx_path = sys.argv[1]
    output_path = sys.argv[2]
    
    try:
        xlsx_to_datajs(xlsx_path, output_path)
    except FileNotFoundError:
        print(f"✗ ملف غير موجود: {xlsx_path}")
        sys.exit(1)
    except Exception as e:
        print(f"✗ خطأ: {e}")
        sys.exit(1)
